### ISSUE TITLE
Prototype milestone tasks

### ISSUE THREAD

**Issue by Joshuaalbert** [Joshuaalbert/DSA2000-Cal#1]
The below tasks are remaining to close off the forward modelling, and are also necessary for prototype.

## Tasks 

- [x] #2
- [x] #3
- [ ] Use Beam
  - [x] #4
  - [x] #5
  - [x] #6
  - [x] #7
  - [x] #8
- [x] #9
- [x] #10
- [x] #11
    - [ ] **Decoherence**: Mean(Abs(Phase - Ground Truth)) <-- Dependence on ionospheric time scale, grows as ionosphere timescale approaches sol int
    - [ ] **Error**: Std(Abs(Phase - Ground Truth)) <-- Dependence on SNR and on ionospheric time scale, as long as no decoherence depends only on SNR
    - [ ] **Time per iteration** <-- Grows with time to predict num_baselines * num sources
    - [ ] **Number of iterations** <-- Should shrink with closeness to optimum, if no decoherence then this SHOULD approach ground-truth
- [x] #12
- [x] #13
  - [ ] Resolve why aterms are not working (Andre conversation)
  - [ ] Turn on PAF
  - [ ] Turn on ionosphere gains  
  - [ ] Turn on dldm screens from instrumental effects
- [x] #14
  - [ ] Make cover channels of interest
  - [ ] Use wholistic approach as in DFT
- [x] #15
- [x] #16
- [x] #17
- [x] #18
