### ISSUE TITLE
Forward modelling run

### ISSUE THREAD

**Issue by Joshuaalbert** [Joshuaalbert/DSA2000-Cal#148]
Goal: to run the first forward modelling, targeting a nominal run:
1. with most up-to-date OVRO antenna model
2. realistic dish effects
3. realistic ionosphere
4. full sky model
5. calibration errors
6. stokes I

Note, this deviates from the original plan of ramping up with fewer things turned on. This is because we have less time now, so we cannot afford to run it many times. We instead opt for comprehensive coverage. This first nominal run will validate the system for a single pointing. We will then procede to do rhw neighbourhood of pointings, completing a single mosaic'd tile.

# Tasks
- [ ] Finalise observation parameters:
  * Choose subband according to how many computational resources are available, using best throughput timings. Aim for no backpressure.
  *  Choose zenith angle (i.e. `ref_time`, and `pointing_center`)
  * Assign pointings in TRECS to survey pointings.
- [ ] Create unresolved bright source catalog covering full survey in wsclean format.
  * These are the bright sources that cause problems normally, so they are synthetically added. Can be a simple random arrangement of 100 5Jy sources, with flat spectral index over 700MHz to 2000MHz.
- [ ] Fix dish aperture simulation and FFT to image plane #142 
- [ ] Rewrite ionosphere simulation with better memory contiguosity #27 
- [ ] Set the resource requirements for each task (`num_cpus`, `num_gpus`, `memory`)
- [ ] Determine why calibration is slower #143
- [ ] Scale up to remove backpressure
