### ISSUE TITLE
Verification of components

### ISSUE THREAD

**Issue by Joshuaalbert** [Joshuaalbert/DSA2000-Cal#78]
We are now at a point where all components are working, and we can simulate for 10.3min observations. However, the resources required to simulate are massive, hence there is only once chance. We also notice some strange observations that hint there are bugs yet to be ironned out. Here I'll list the strange observations, and verifications.

## Strange observations
- [x] #79
- [x] #80
- [x] #110

## Verify
- [x] #81
- [x] #82
- [x] #83
- [x] #84
- [x] #85
- [x] #86
- [ ] #90
- [ ] #91

**Comment by Joshuaalbert** [comment]
We are now at a point where all components are working, and we can simulate for 10.3min observations. However, the resources required to simulate are massive, hence there is only once chance. We also notice some strange observations that hint there are bugs yet to be ironned out. Here I'll list the strange observations, and verifications.

## Strange observations
- [ ] Negative RFI sources when imaged
- [ ] A constant mean background for single channel image, `0.0330027 Jy`, stddev `0.000792852 Jy`

## Verify
- [ ] RIME models for points
- [ ] RIME model for gaussians
- [ ] RIME model for FITS
- [ ] RIME model for RFI
- [ ] Imaging with PB correction
- [ ] Calibration with random diagonal antenna-based gains
